### PR TITLE
Sort enum values

### PR DESCRIPTION
**Pull request by MyrikLD**
Sort enum values to prevent every time changes after schema generation.

### CODE REVIEW

**Comment by barbieri** [comment]
thanks, would you mind to merge both commits in only one and also call the scripts in each example so their schema are updated?

**Comment by MyrikLD** [comment]
> thanks, would you mind to merge both commits in only one and also call the scripts in each example so their schema are updated?

I updated github example but shopify asks me to create shop to get OAuth token. Maybe, owners of sgqlc-test shop could use their token to update examples here?

**Comment by MyrikLD** [comment]
@barbieri Check now

**Comment by barbieri** [comment]
sorry taking so long, I was out during the weekend. I did check it right now, code is good, but the `github_schema.py` wasn't fully updated, it lacked the descriptions (we're using it in that example since that feature was introduced).

So I did the amend in your commit and pushed it to master.

**Pull request closed without merging**
