### PR TITLE
Sort enum doctype

### PR DESCRIPTION
**Pull request by MyrikLD**
Sort enum docstring to prevent every time changes after schema generation.

### CODE REVIEW

**Comment by barbieri** [comment]
@MyrikLD code looks good, checks failed due some strange reason, #178  failed due the same, likely I'll need to update the Pipfile.

As for the code, while I see your point, I noticed most of the time the enums are serialized as a list, handled as some ordered dict... that is, the order is not supposed to change. Could you clarify in which circumstances it was changing? My only concern is that eventually we'll be changing the order when we should not, say `COMMON` was supposed to be the first enum value, since it has some more usage than `ANOTHER_LESS_COMMON_OPTION`.

**Comment by barbieri** [comment]
I tried to fix the github action checks, please rebase and push-force it so they will run again?

**Comment by MyrikLD** [comment]
> @MyrikLD code looks good, checks failed due some strange reason, #178 failed due the same, likely I'll need to update the Pipfile.
> 
> As for the code, while I see your point, I noticed most of the time the enums are serialized as a list, handled as some ordered dict... that is, the order is not supposed to change. Could you clarify in which circumstances it was changing? My only concern is that eventually we'll be changing the order when we should not, say `COMMON` was supposed to be the first enum value, since it has some more usage than `ANOTHER_LESS_COMMON_OPTION`.

I use introspection of another api. I dont know how it works inside but every time I receive another result. It is too hard to review every comment after new introspection.

**Comment by barbieri** [comment]
sorry taking so long, I did rebase this one and pushed to master as 30a3b6a2acf2798e29f63be0669abc30bb6c911b

**Comment by barbieri** [comment]
closed by 30a3b6a2acf2798e29f63be0669abc30bb6c911b

**Pull request closed without merging**
