### PR TITLE
codegen: Sort types by name

### PR DESCRIPTION
**Pull request by lubo**
I'm unsure whether this resolves the whole #19, but right now, this is all I need.

### CODE REVIEW

**Comment by barbieri** [comment]
thanks, merged

**Comment by lubo** [comment]
Rebase? That's unfortunate… Anyway, thanks for the merge.

**Comment by barbieri** [comment]
matter of personal preference, I'd say. In all the projects I work we use rebase and avoid merge-commits :-)

**Comment by lubo** [comment]
Not really, merge and rebase are not the same thing. Now, our branches diverge as if they don't contain the same changes, even though they do. Also, you could have done fast-forward merge (without the merge commit) in this case… Please, don't take this wrong, but you've made my situation a bit more complicated by doing that rebase and I just hope we could prevent that in the future.

**Comment by barbieri** [comment]
i know what you mean, unfortunately I've used the GH webui to do that, not sure the steps it takes.

when I have access to my dev machine I usually go with `git merge --ff-only` and then push.

**Comment by barbieri** [comment]
this is now in release v6.

again thanks for the patch and sorry about the rebase annoyance.

**Pull request merged**
