### PR TITLE
Correctly handle None as value for Input

### PR DESCRIPTION
**Pull request by jkbak**
Fixes: #163

### CODE REVIEW

**Comment by barbieri** [comment]
@jkbak tests are failing since we lack a test for that new line. Could you provide one? Follow the other documentation in the files, using doctest.

**Comment by jkbak** [comment]
> @jkbak tests are failing since we lack a test for that new line. Could you provide one? Follow the other documentation in the files, using doctest.

@barbieri done

**Comment by barbieri** [comment]
thans @jkbak!

**Comment by jkbak** [comment]
@barbieri would it be possible to get a patch release like 14.0.1?

**Comment by barbieri** [comment]
@jkbak https://pypi.org/project/sgqlc/14.1/ is out

**Pull request merged**
